# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/configuration/#theme-parameters

colorScheme = "avocado"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
# logo = 'blowfish.png'

# mainSections = ["section1", "section2"]
robots = "all"
# defaultBackgroundImage = "everything_everywhere_all_at_once.webp"
defaultBackgroundImage = "bg.webp"

[header]
  layout = "fixed"

[footer]
  showCopyright = true
  # showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  # valid options: page, profile, hero, background, card, custom
  layout = "background"
  showRecent = true
  showRecentItems = 5
  showMoreLink = false
  showMoreLinkDest = "/posts"
  cardView = false
  layoutBackgroundBlur = true
  homepageImage = "/bg.webp"

[article]
  showDate = false
  #showViews = true
  #showLikes = true
  showDateUpdated = true
  showAuthor = true
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = true
  showDraftLabel = false
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showAuthorsBadges = false 
  showWordCount = true
  showSummary = false
  sharingLinks = []
  # sharingLinks = [ "linkedin", "twitter", "whatsapp", "pinterest", "reddit", "facebook", "email"]

[list]
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = true
  showCards = true
  groupByYear = true

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true

[firebase]
  # apiKey = "XXXXXX"
  # authDomain = "XXXXXX"
  # projectId = "XXXXXX"
  # storageBucket = "XXXXXX"
  # messagingSenderId = "XXXXXX"
  # appId = "XXXXXX"
  # measurementId = "XXXXXX"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
